const primary = "#F5A623";
const primaryDark = "#D4891A";

export default {
  light: {
    text: "#1A1A2E",
    textSecondary: "#6B7280",
    textTertiary: "#9CA3AF",
    background: "#F8F9FA",
    backgroundSecondary: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceSecondary: "#F1F3F5",
    border: "#E5E7EB",
    borderLight: "#F3F4F6",
    primary,
    primaryDark,
    accent: "#4F46E5",
    danger: "#EF4444",
    success: "#10B981",
    tint: primary,
    tabIconDefault: "#9CA3AF",
    tabIconSelected: primary,
    overlay: "rgba(0, 0, 0, 0.5)",
    card: "#FFFFFF",
    shadow: "rgba(0,0,0,0.08)",
    sliderTrack: "#E5E7EB",
    sliderFill: primary,
    fab: primary,
    fabIcon: "#FFFFFF",
  },
  dark: {
    text: "#F9FAFB",
    textSecondary: "#9CA3AF",
    textTertiary: "#6B7280",
    background: "#0D0D14",
    backgroundSecondary: "#1A1A2E",
    surface: "#1E1E30",
    surfaceSecondary: "#252538",
    border: "#2E2E44",
    borderLight: "#252538",
    primary,
    primaryDark,
    accent: "#6366F1",
    danger: "#F87171",
    success: "#34D399",
    tint: primary,
    tabIconDefault: "#6B7280",
    tabIconSelected: primary,
    overlay: "rgba(0, 0, 0, 0.7)",
    card: "#1E1E30",
    shadow: "rgba(0,0,0,0.4)",
    sliderTrack: "#2E2E44",
    sliderFill: primary,
    fab: primary,
    fabIcon: "#FFFFFF",
  },
};
